### ISSUE TITLE
A recipe for Symfony Flex

### ISSUE THREAD

**Issue by covex-nn** [sonata-project/media-odm-pack#2]
It was easier, than i expected

To test a recipe execute following commands:

```bash
composer create-project symfony/skeleton .
composer require alcaeus/mongo-php-adapter sonata-project/doctrine-mongodb-admin-bundle sonata-project/media-bundle
```

Copy files from [gist](https://gist.github.com/covex-nn/2e9a5f872eb008b7bb4bae52eb11a882) to `src/Document`

Create `config/packages/sonata_media_odm.yaml`

```yaml
sonata_media:
    class:
        media: App\Document\SonataMediaMedia
        gallery: App\Document\SonataMediaGallery
        gallery_has_media: App\Document\SonataMediaGalleryHasMedia
    db_driver: doctrine_mongodb
```

Create `docker-compose.yaml`

```yaml
version: '3.4'

services:
    mongo:
        image: mongo:3.6
        ports:
            - "27017:27017"
        environment:
            MONGO_DATA_DIR: /data/db
        volumes:
          - database:/data/db

volumes:
    database:
```

Execute commands:

```bash
docker-compose up -d
composer auto-scripts
bin/console doctrine:mongodb:schema:create
php -S 127.0.0.1:80 -t public
```

Also, under Windows i updated `.env` file: i changed IP here `MONGODB_URL=mongodb://127.0.0.1:27017` to a IP from result of `docker-machine env`

Visit http://localhost/admin/
